import 'package:flutter/material.dart';

/// In-app localization dictionary matching web app translations.
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('uk'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'uk': {
      // Navigation
      'app_title': 'Шкільний Щоденник',
      'nav_schedule': 'Розклад',
      'nav_homework': 'Д/З',
      'nav_notes': 'Нотатки',
      'nav_stats': 'Статистика',
      'nav_settings': 'Налаштування',

      // Schedule & Daily
      'today': 'Сьогодні',
      'now': 'Зараз',
      'ongoing': 'Триває',
      'upcoming': 'Наступний',
      'no_lessons': 'Немає уроків',
      'no_lessons_scheduled': 'На цей день немає запланованих уроків',
      'numerator_week': 'Чисельник',
      'denominator_week': 'Знаменник',
      'week': 'Тиждень',
      'lesson': 'урок',
      'break_now': 'Перерва',
      'cab': 'каб.',
      'teacher': 'Вчитель',
      'consultation': 'Консультація',
      'cancelled': 'Скасовано',
      'control_work': 'Контрольна робота',
      'test': 'Самостійна робота',
      'essay': 'Твір / Есе',
      'project': 'Проєкт',
      'change_lesson': 'Зміна уроку на дату',
      'academic_event': 'Академічна подія',
      'event_none': 'Звичайний урок',
      'cancel_lesson': 'Скасувати цей урок (вікно / немає уроку)',
      'cancel_lesson_desc':
          'У щоденнику відображатиметься як скасований із закресленням',
      'air_alert_cancel': 'Повітряна тривога (скасувати)',
      'air_alert_cancel_desc':
          'Швидко позначити цей урок скасованим через тривогу',
      'consultation_skip': 'Консультація (пропустити)',
      'consultation_skip_desc':
          'Консультація необовʼязкова. 1 клік — позначити пропущеною',
      'substitute_subject': 'Урок на заміну (новий предмет)',
      'substitute_subject_desc': 'Оберіть інший предмет для заміни',
      'select_subject': 'Оберіть предмет',
      'search_subject': 'Пошук предмета...',
      'override_note': 'Примітка / Причина (необовʼязково)',
      'override_note_hint': 'Наприклад, Заміна викладача або тема тесту',
      'reset_to_regular': 'Повернути регулярний розклад',
      'reset_confirm': 'Повернути регулярний розклад для цього уроку?',
      'next_lesson': 'Наступний урок',
      'previous_lesson': 'Попередній урок',
      'no_next_lesson': 'Не знайдено наступного уроку для цього предмета.',
      'no_prev_lesson': 'Не знайдено попереднього уроку для цього предмета.',
      'finding_lesson': 'Пошук уроку...',
      'lesson_override_saved': 'Зміни успішно збережено',
      'lesson_override_deleted': 'Регулярний розклад відновлено',
      'diary_preview': 'Відображення у щоденнику:',

      // Days of week
      'mon': 'Пн',
      'tue': 'Вт',
      'wed': 'Ср',
      'thu': 'Чт',
      'fri': 'Пт',
      'sat': 'Сб',
      'sun': 'Нд',
      'monday': 'Понеділок',
      'tuesday': 'Вівторок',
      'wednesday': 'Середа',
      'thursday': 'Четвер',
      'friday': 'П\'ятниця',
      'saturday': 'Субота',
      'sunday': 'Неділя',

      // Homework
      'homework': 'Домашні завдання',
      'pending': 'До виконання',
      'completed': 'Виконано',
      'failed': 'Не здано',
      'all': 'Всі',
      'due_date': 'Термін здачі',
      'add_homework': 'Додати Д/З',
      'edit_homework': 'Редагувати Д/З',
      'time_spent': 'Витрачено часу',
      'minutes': 'хв',
      'seconds': 'сек',
      'attachments': 'Вкладення',
      'add_photo': 'Додати фото',
      'camera': 'Камера',
      'gallery': 'Галерея',
      'attach_file': 'Прикріпити файл',
      'no_homework': 'Немає домашніх завдань',

      // Notes
      'lesson_notes': 'Нотатки уроків',
      'add_note': 'Додати нотатку',
      'edit_note': 'Редагувати нотатку',
      'note_text': 'Текст нотатки',
      'search_notes': 'Пошук нотаток...',
      'no_notes': 'Немає нотаток для цього уроку',

      // Subjects & Bells
      'subjects': 'Предмети',
      'add_subject': 'Додати предмет',
      'subject_name': 'Назва предмета',
      'short_name': 'Скорочена назва',
      'color': 'Колір',
      'default_cabinet': 'Кабінет за замовчуванням',
      'bells': 'Розклад дзвінків',
      'add_bell': 'Додати дзвінок',
      'start_time': 'Початок',
      'end_time': 'Кінець',

      // Stats
      'statistics': 'Статистика',
      'weekly_overview': 'Огляд за тиждень',
      'study_time': 'Час навчання',
      'homework_rate': 'Виконання Д/З',
      'total_lessons': 'Всього уроків',
      'hours_short': 'год',
      'minutes_short': 'хв',
      'busiest_subject': 'Найбільше часу',
      'total_hours': 'Загальний час навчання',
      'stats_subjects_count': 'Кількість предметів',
      'stats_lessons_count': 'Кількість уроків',
      'stats_per_day': 'в день',
      'stats_homework_rate': 'Виконання завдань',
      'stats_completed': 'здано',
      'stats_failed': 'не здано',
      'stats_pending': 'в процесі',
      'stats_homework_time': 'Час на Д/З',
      'stats_avg_homework_time': 'середній час на завдання',
      'stats_failed_title': 'Не здані домашні завдання',
      'stats_failed_desc': 'Завдання, які не були здані вчасно на уроці',
      'stats_breaks_duration': 'Тривалість перерв',
      'stats_cancelled_lessons': 'Скасовані уроки',
      'stats_cancellation_reasons': 'Причини скасування',
      'stats_reason_not_specified': 'Причина не вказана',
      'stats_events_summary': 'Академічні контролі',
      'stats_mode_actual': 'Фактичний',
      'stats_mode_numerator': 'Чисельник',
      'stats_mode_denominator': 'Знаменник',
      'stats_metric_time': 'Час',
      'stats_metric_lessons': 'Уроки',
      'by_subjects': 'За предметами',
      'by_days': 'За днями',
      'daily_breakdown': 'Розклад по днях',
      'day_lessons': 'уроків',
      'day_no_lessons': 'Немає запланованих уроків',
      'no_data_week': 'Немає даних за цей тиждень',
      'event_control_work': 'Контрольна',
      'event_test': 'Тест',
      'event_essay': 'Твір',
      'event_project': 'Проєкт',
      'breaks_and_cancellations': 'Перерви та скасовані уроки',
      'duration': 'Тривалість',
      'hw_failed_badge': 'Не здано',

      // Server & Sync
      'server_connection': 'Підключення до сервера',
      'server_url': 'Адреса сервера (Docker)',
      'server_url_hint': 'наприклад http://192.168.1.100:8080',
      'test_connection': 'Перевірити з\'єднання',
      'connection_ok': 'З\'єднання успішне! Сервер доступний.',
      'connection_failed': 'Не вдалося підключитися до сервера.',
      'server_unreachable_title': 'Сервер недоступний',
      'server_unreachable_desc':
          'Не вдалося з\'єднатися із сервером. Перевірте адресу у локальній мережі.',
      'configure_server_btn': 'Налаштувати адресу',
      'retry': 'Спробувати знову',
      'sync_status': 'Стан синхронізації',
      'sync_now': 'Синхронізувати зараз',
      'synced': 'Синхронізовано',
      'syncing': 'Синхронізація...',
      'auto_sync': 'Авто-синхронізація',
      'auto_sync_desc':
          'Автоматично оновлювати розклад та синхронізувати зміни',
      'sync_interval': 'Інтервал авто-оновлення',
      'sync_interval_15s': '15 с',
      'sync_interval_30s': '30 с',
      'sync_interval_1m': '1 хв',
      'sync_interval_5m': '5 хв',
      'last_sync_time': 'Останнє оновлення',
      'just_now': 'щойно',
      'seconds_ago': 'с тому',
      'minutes_ago': 'хв тому',
      'never_synced': 'ще не синхронізовано',
      'sync_success': 'Синхронізація завершена',
      'sync_failed': 'Помилка синхронізації',
      'offline_mode': 'Офлайн режим (локальна база)',
      'pending_sync': 'Очікують відправки на сервер',
      'save_and_continue': 'Зберегти та продовжити',
      'tailscale_fallback': 'Резервний сервер (Tailscale)',
      'tailscale_url': 'Адреса Tailscale (Tailnet IP)',
      'tailscale_url_hint': 'наприклад http://100.x.y.z:8080',
      'tailscale_desc':
          'Автоматичний перехід на Tailnet IP у разі недоступності основного сервера',
      'tailscale_active': 'Використовується резервний канал Tailscale',
      'tailscale_not_configured': 'Не налаштовано',
      'primary_server': 'Основний сервер (LAN)',
      'fallback_server': 'Резервний сервер (Tailscale)',
      'test_primary': 'Перевірити основний',
      'test_tailscale': 'Перевірити Tailscale',
      'tailscale_ok': 'З\'єднання з Tailscale успішне!',
      'tailscale_failed': 'Не вдалося з\'єднатися з Tailscale IP',

      // Air Raid Alerts
      'air_raid_alert': 'Повітряна тривога',
      'alert_active': 'Увага! Повітряна тривога у вашому регіоні!',
      'alert_calm': 'Повітряної тривоги немає',
      'select_region': 'Область для моніторингу тривог',

      // Common actions
      'save': 'Зберегти',
      'cancel': 'Скасувати',
      'delete': 'Видалити',
      'edit': 'Редагувати',
      'close': 'Закрити',
      'language': 'Мова інтерфейсу',
      'theme': 'Тема оформлення',
      'theme_dark': 'Темна',
      'theme_light': 'Світла',
      'theme_system': 'Системна',

      // Display & Performance
      'display_settings': 'Відображення та інтерфейс',
      'show_classrooms': 'Показувати кабінети',
      'show_classrooms_desc': 'Відображати номери кабінетів у розкладі занять',
      'skip_weekends': 'Пропускати вихідні',
      'skip_weekends_desc': 'Автоматично відкривати понеділок у вихідні дні',
      'performance_mode': 'Плавне гортання (FPS)',
      'performance_mode_desc':
          'Оптимізація графіки без затримок для 60/120 FPS',

      // File Downloading & Storage
      'download_file': 'Завантажити файл',
      'download_image': 'Завантажити фото',
      'file_downloading': 'Завантаження файлу...',
      'file_saved_to_downloads': 'Файл збережено в Завантаження',
      'file_download_error': 'Помилка завантаження файлу',
      'open_file': 'Відкрити',
      'wipe_all_data': 'Видалити всі локальні дані',
      'wipe_all_data_desc':
          'Очистити всі кешовані уроки, Д/З, нотатки, предмети, дзвінки та завантажені файли з пристрою',
      'wipe_all_confirm_title': 'Видалити всі дані з пристрою?',
      'wipe_all_confirm_desc':
          'Це повністю видалить усі збережені розклади, домашні завдання, нотатки, предмети, дзвінки, чергу офлайн-синхронізації та вкладення на цьому телефоні. Дія незворотна!',
      'wipe_all_success': 'Усі локальні дані успішно видалено',
      'wipe_all_btn': 'Видалити все',
    },
    'en': {
      // Navigation
      'app_title': 'School Diary',
      'nav_schedule': 'Schedule',
      'nav_homework': 'Homework',
      'nav_notes': 'Notes',
      'nav_stats': 'Stats',
      'nav_settings': 'Settings',

      // Schedule & Daily
      'today': 'Today',
      'now': 'Now',
      'ongoing': 'Ongoing',
      'upcoming': 'Upcoming',
      'no_lessons': 'No lessons',
      'no_lessons_scheduled': 'No lessons scheduled for this day',
      'numerator_week': 'Numerator',
      'denominator_week': 'Denominator',
      'week': 'Week',
      'lesson': 'lesson',
      'break_now': 'Break',
      'cab': 'Cab.',
      'teacher': 'Teacher',
      'consultation': 'Consultation',
      'cancelled': 'Cancelled',
      'control_work': 'Control Work',
      'test': 'Test',
      'essay': 'Essay',
      'project': 'Project',
      'change_lesson': 'Change Lesson for Date',
      'academic_event': 'Academic Event',
      'event_none': 'Regular Lesson',
      'cancel_lesson': 'Cancel lesson (no class today)',
      'cancel_lesson_desc':
          'Displays in diary with strikethrough indicating no lesson',
      'air_alert_cancel': 'Air Alert (Cancel Lesson)',
      'air_alert_cancel_desc':
          '1-click mark lesson as cancelled due to air raid alert',
      'consultation_skip': 'Consultation (Skip Class)',
      'consultation_skip_desc':
          'Consultations are optional. 1-click mark as skipped',
      'substitute_subject': 'Substitute Subject (New Class)',
      'substitute_subject_desc': 'Select another subject for substitution',
      'select_subject': 'Select Subject',
      'search_subject': 'Search subjects...',
      'override_note': 'Note / Reason (optional)',
      'override_note_hint': 'e.g. Teacher substitution or test topic',
      'reset_to_regular': 'Reset to Regular Schedule',
      'reset_confirm': 'Reset this lesson to the regular recurring schedule?',
      'next_lesson': 'Next Lesson',
      'previous_lesson': 'Previous Lesson',
      'no_next_lesson': 'No upcoming lesson found for this subject.',
      'no_prev_lesson': 'No previous lesson found for this subject.',
      'finding_lesson': 'Locating lesson...',
      'lesson_override_saved': 'Changes saved successfully',
      'lesson_override_deleted': 'Regular schedule restored',
      'diary_preview': 'Appearance in diary:',

      // Days of week
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',

      // Homework
      'homework': 'Homework',
      'pending': 'Pending',
      'completed': 'Completed',
      'failed': 'Failed',
      'all': 'All',
      'due_date': 'Due Date',
      'add_homework': 'Add Homework',
      'edit_homework': 'Edit Homework',
      'time_spent': 'Time Spent',
      'minutes': 'min',
      'seconds': 'sec',
      'attachments': 'Attachments',
      'add_photo': 'Add Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'attach_file': 'Attach File',
      'no_homework': 'No homework assigned',

      // Notes
      'lesson_notes': 'Lesson Notes',
      'add_note': 'Add Note',
      'edit_note': 'Edit Note',
      'note_text': 'Note content',
      'search_notes': 'Search notes...',
      'no_notes': 'No notes for this lesson',

      // Subjects & Bells
      'subjects': 'Subjects',
      'add_subject': 'Add Subject',
      'subject_name': 'Subject Name',
      'short_name': 'Short Name',
      'color': 'Color',
      'default_cabinet': 'Default Cabinet',
      'bells': 'Bell Schedule',
      'add_bell': 'Add Bell',
      'start_time': 'Start Time',
      'end_time': 'End Time',

      // Stats
      'statistics': 'Statistics',
      'weekly_overview': 'Weekly Overview',
      'study_time': 'Study Time',
      'homework_rate': 'HW Completion',
      'total_lessons': 'Total Lessons',
      'hours_short': 'h',
      'minutes_short': 'm',
      'busiest_subject': 'Busiest Subject',
      'total_hours': 'Total Study Time',
      'stats_subjects_count': 'Total Subjects',
      'stats_lessons_count': 'Lessons Scheduled',
      'stats_per_day': 'per day',
      'stats_homework_rate': 'Homework Rate',
      'stats_completed': 'completed',
      'stats_failed': 'failed',
      'stats_pending': 'pending',
      'stats_homework_time': 'Homework Time',
      'stats_avg_homework_time': 'avg. time per assignment',
      'stats_failed_title': 'Failed Homework in Class',
      'stats_failed_desc': 'Assignments marked as not completed on time',
      'stats_breaks_duration': 'Breaks Duration',
      'stats_cancelled_lessons': 'Cancelled Lessons',
      'stats_cancellation_reasons': 'Cancellation Reasons',
      'stats_reason_not_specified': 'Reason not specified',
      'stats_events_summary': 'Academic Events',
      'stats_mode_actual': 'Actual',
      'stats_mode_numerator': 'Numerator',
      'stats_mode_denominator': 'Denominator',
      'stats_metric_time': 'Time',
      'stats_metric_lessons': 'Lessons',
      'by_subjects': 'By Subjects',
      'by_days': 'By Days',
      'daily_breakdown': 'Daily Breakdown',
      'day_lessons': 'lessons',
      'day_no_lessons': 'No lessons scheduled',
      'no_data_week': 'No data for this week',
      'event_control_work': 'Control Work',
      'event_test': 'Test',
      'event_essay': 'Essay',
      'event_project': 'Project',
      'breaks_and_cancellations': 'Breaks & Schedule Interruptions',
      'duration': 'Duration',
      'hw_failed_badge': 'Failed',

      // Server & Sync
      'server_connection': 'Server Connection',
      'server_url': 'Server Address (Docker)',
      'server_url_hint': 'e.g. http://192.168.1.100:8080',
      'test_connection': 'Test Connection',
      'connection_ok': 'Connected successfully! Server is healthy.',
      'connection_failed': 'Could not connect to server.',
      'server_unreachable_title': 'Server Unreachable',
      'server_unreachable_desc':
          'Could not reach server. Check local network IP or configure in Settings.',
      'configure_server_btn': 'Configure Address',
      'retry': 'Retry',
      'sync_status': 'Sync Status',
      'sync_now': 'Sync Now',
      'synced': 'Synced',
      'syncing': 'Syncing...',
      'auto_sync': 'Auto-Sync',
      'auto_sync_desc': 'Automatically refresh schedule and sync changes',
      'sync_interval': 'Auto-Sync Interval',
      'sync_interval_15s': '15s',
      'sync_interval_30s': '30s',
      'sync_interval_1m': '1m',
      'sync_interval_5m': '5m',
      'last_sync_time': 'Last synced',
      'just_now': 'just now',
      'seconds_ago': 's ago',
      'minutes_ago': 'm ago',
      'never_synced': 'never',
      'sync_success': 'Sync completed successfully',
      'sync_failed': 'Sync failed',
      'offline_mode': 'Offline Mode (Local Cache)',
      'pending_sync': 'Pending Sync Queue',
      'save_and_continue': 'Save & Continue',
      'tailscale_fallback': 'Fallback Server (Tailscale)',
      'tailscale_url': 'Tailscale Address (Tailnet IP)',
      'tailscale_url_hint': 'e.g. http://100.x.y.z:8080',
      'tailscale_desc':
          'Automatic failover to Tailnet IP if primary server is unreachable',
      'tailscale_active': 'Using Tailscale fallback channel',
      'tailscale_not_configured': 'Not configured',
      'primary_server': 'Primary Server (LAN)',
      'fallback_server': 'Fallback Server (Tailscale)',
      'test_primary': 'Test Primary',
      'test_tailscale': 'Test Tailscale',
      'tailscale_ok': 'Tailscale connection successful!',
      'tailscale_failed': 'Could not connect to Tailscale IP',

      // Air Raid Alerts
      'air_raid_alert': 'Air Raid Alert',
      'alert_active': 'Warning! Air raid alert in your region!',
      'alert_calm': 'No active air raid alert',
      'select_region': 'Region for Alert Monitoring',

      // Common actions
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'language': 'Language',
      'theme': 'Theme',
      'theme_dark': 'Dark',
      'theme_light': 'Light',
      'theme_system': 'System',

      // Display & Performance
      'display_settings': 'Display & Interface',
      'show_classrooms': 'Show Classrooms',
      'show_classrooms_desc': 'Display classroom numbers in schedule view',
      'skip_weekends': 'Skip Weekends to Monday',
      'skip_weekends_desc': 'Automatically switch to Monday on weekends',
      'performance_mode': 'Smooth Scrolling (FPS)',
      'performance_mode_desc':
          'Optimized rendering for responsive 60/120 FPS scrolling',

      // File Downloading & Storage
      'download_file': 'Download file',
      'download_image': 'Download image',
      'file_downloading': 'Downloading file...',
      'file_saved_to_downloads': 'File saved to Downloads',
      'file_download_error': 'Failed to download file',
      'open_file': 'Open',
      'wipe_all_data': 'Delete Entirely All Local Data',
      'wipe_all_data_desc':
          'Permanently delete all cached schedules, homework, notes, subjects, bells, and staged files from this device',
      'wipe_all_confirm_title': 'Delete ALL Local Data?',
      'wipe_all_confirm_desc':
          'This will permanently wipe all cached lessons, homework, notes, bells, subjects, staged local files, and offline sync queue on this device. This action cannot be undone!',
      'wipe_all_success': 'All local data has been completely deleted',
      'wipe_all_btn': 'Delete Everything',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['uk', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
