import 'package:flutter/material.dart';

/// In-app localization dictionary matching web app translations.
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('uk'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'uk': {
      // Navigation
      'app_title': 'Шкільний Щоденник',
      'nav_schedule': 'Розклад',
      'nav_homework': 'Д/З',
      'nav_notes': 'Нотатки',
      'nav_stats': 'Статистика',
      'nav_settings': 'Налаштування',

      // Schedule & Daily
      'today': 'Сьогодні',
      'now': 'Зараз',
      'ongoing': 'Триває',
      'upcoming': 'Наступний',
      'no_lessons': 'Немає уроків',
      'no_lessons_scheduled': 'На цей день немає запланованих уроків',
      'numerator_week': 'Чисельник',
      'denominator_week': 'Знаменник',
      'week': 'Тиждень',
      'lesson': 'урок',
      'break_now': 'Перерва',
      'cab': 'каб.',
      'teacher': 'Вчитель',
      'consultation': 'Консультація',
      'cancelled': 'Скасовано',
      'control_work': 'Контрольна робота',
      'test': 'Самостійна робота',
      'essay': 'Твір / Есе',
      'project': 'Проєкт',

      // Days of week
      'mon': 'Пн',
      'tue': 'Вт',
      'wed': 'Ср',
      'thu': 'Чт',
      'fri': 'Пт',
      'sat': 'Сб',
      'sun': 'Нд',
      'monday': 'Понеділок',
      'tuesday': 'Вівторок',
      'wednesday': 'Середа',
      'thursday': 'Четвер',
      'friday': 'П\'ятниця',
      'saturday': 'Субота',
      'sunday': 'Неділя',

      // Homework
      'homework': 'Домашні завдання',
      'pending': 'До виконання',
      'completed': 'Виконано',
      'failed': 'Не здано',
      'all': 'Всі',
      'due_date': 'Термін здачі',
      'add_homework': 'Додати Д/З',
      'edit_homework': 'Редагувати Д/З',
      'time_spent': 'Витрачено часу',
      'minutes': 'хв',
      'seconds': 'сек',
      'attachments': 'Вкладення',
      'add_photo': 'Додати фото',
      'camera': 'Камера',
      'gallery': 'Галерея',
      'attach_file': 'Прикріпити файл',
      'no_homework': 'Немає домашніх завдань',

      // Notes
      'lesson_notes': 'Нотатки уроків',
      'add_note': 'Додати нотатку',
      'edit_note': 'Редагувати нотатку',
      'note_text': 'Текст нотатки',
      'search_notes': 'Пошук нотаток...',
      'no_notes': 'Немає нотаток для цього уроку',

      // Subjects & Bells
      'subjects': 'Предмети',
      'add_subject': 'Додати предмет',
      'subject_name': 'Назва предмета',
      'short_name': 'Скорочена назва',
      'color': 'Колір',
      'default_cabinet': 'Кабінет за замовчуванням',
      'bells': 'Розклад дзвінків',
      'add_bell': 'Додати дзвінок',
      'start_time': 'Початок',
      'end_time': 'Кінець',

      // Stats
      'statistics': 'Статистика',
      'weekly_overview': 'Огляд за тиждень',
      'study_time': 'Час навчання',
      'homework_rate': 'Виконання Д/З',
      'total_lessons': 'Всього уроків',
      'hours_short': 'год',
      'minutes_short': 'хв',
      'busiest_subject': 'Найбільше часу',
      'total_hours': 'Загальний час навчання',
      'stats_subjects_count': 'Кількість предметів',
      'stats_lessons_count': 'Кількість уроків',
      'stats_per_day': 'в день',
      'stats_homework_rate': 'Виконання завдань',
      'stats_completed': 'здано',
      'stats_failed': 'не здано',
      'stats_pending': 'в процесі',
      'stats_homework_time': 'Час на Д/З',
      'stats_avg_homework_time': 'середній час на завдання',
      'stats_failed_title': 'Не здані домашні завдання',
      'stats_failed_desc': 'Завдання, які не були здані вчасно на уроці',
      'stats_breaks_duration': 'Тривалість перерв',
      'stats_cancelled_lessons': 'Скасовані уроки',
      'stats_cancellation_reasons': 'Причини скасування',
      'stats_reason_not_specified': 'Причина не вказана',
      'stats_events_summary': 'Академічні контролі',
      'stats_mode_actual': 'Фактичний',
      'stats_mode_numerator': 'Чисельник',
      'stats_mode_denominator': 'Знаменник',
      'stats_metric_time': 'Час',
      'stats_metric_lessons': 'Уроки',
      'by_subjects': 'За предметами',
      'by_days': 'За днями',
      'daily_breakdown': 'Розклад по днях',
      'day_lessons': 'уроків',
      'day_no_lessons': 'Немає запланованих уроків',
      'no_data_week': 'Немає даних за цей тиждень',
      'event_control_work': 'Контрольна',
      'event_test': 'Тест',
      'event_essay': 'Твір',
      'event_project': 'Проєкт',
      'breaks_and_cancellations': 'Перерви та скасовані уроки',
      'duration': 'Тривалість',
      'hw_failed_badge': 'Не здано',

      // Server & Sync
      'server_connection': 'Підключення до сервера',
      'server_url': 'Адреса сервера (Docker)',
      'server_url_hint': 'наприклад http://192.168.1.100:8080',
      'test_connection': 'Перевірити з\'єднання',
      'connection_ok': 'З\'єднання успішне! Сервер доступний.',
      'connection_failed': 'Не вдалося підключитися до сервера.',
      'server_unreachable_title': 'Сервер недоступний',
      'server_unreachable_desc': 'Не вдалося з\'єднатися із сервером. Перевірте адресу у локальній мережі.',
      'configure_server_btn': 'Налаштувати адресу',
      'retry': 'Спробувати знову',
      'sync_status': 'Стан синхронізації',
      'sync_now': 'Синхронізувати зараз',
      'synced': 'Синхронізовано',
      'syncing': 'Синхронізація...',
      'auto_sync': 'Авто-синхронізація',
      'auto_sync_desc': 'Автоматично оновлювати розклад та синхронізувати зміни',
      'sync_interval': 'Інтервал авто-оновлення',
      'sync_interval_15s': '15 с',
      'sync_interval_30s': '30 с',
      'sync_interval_1m': '1 хв',
      'sync_interval_5m': '5 хв',
      'last_sync_time': 'Останнє оновлення',
      'just_now': 'щойно',
      'seconds_ago': 'с тому',
      'minutes_ago': 'хв тому',
      'never_synced': 'ще не синхронізовано',
      'sync_success': 'Синхронізація завершена',
      'sync_failed': 'Помилка синхронізації',
      'offline_mode': 'Офлайн режим (локальна база)',
      'pending_sync': 'Очікують відправки на сервер',
      'save_and_continue': 'Зберегти та продовжити',

      // Air Raid Alerts
      'air_raid_alert': 'Повітряна тривога',
      'alert_active': 'Увага! Повітряна тривога у вашому регіоні!',
      'alert_calm': 'Повітряної тривоги немає',
      'select_region': 'Область для моніторингу тривог',

      // Common actions
      'save': 'Зберегти',
      'cancel': 'Скасувати',
      'delete': 'Видалити',
      'edit': 'Редагувати',
      'close': 'Закрити',
      'language': 'Мова інтерфейсу',
      'theme': 'Тема оформлення',
      'theme_dark': 'Темна',
      'theme_light': 'Світла',
      'theme_system': 'Системна',
    },
    'en': {
      // Navigation
      'app_title': 'School Diary',
      'nav_schedule': 'Schedule',
      'nav_homework': 'Homework',
      'nav_notes': 'Notes',
      'nav_stats': 'Stats',
      'nav_settings': 'Settings',

      // Schedule & Daily
      'today': 'Today',
      'now': 'Now',
      'ongoing': 'Ongoing',
      'upcoming': 'Upcoming',
      'no_lessons': 'No lessons',
      'no_lessons_scheduled': 'No lessons scheduled for this day',
      'numerator_week': 'Numerator',
      'denominator_week': 'Denominator',
      'week': 'Week',
      'lesson': 'lesson',
      'break_now': 'Break',
      'cab': 'Cab.',
      'teacher': 'Teacher',
      'consultation': 'Consultation',
      'cancelled': 'Cancelled',
      'control_work': 'Control Work',
      'test': 'Test',
      'essay': 'Essay',
      'project': 'Project',

      // Days of week
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',

      // Homework
      'homework': 'Homework',
      'pending': 'Pending',
      'completed': 'Completed',
      'failed': 'Failed',
      'all': 'All',
      'due_date': 'Due Date',
      'add_homework': 'Add Homework',
      'edit_homework': 'Edit Homework',
      'time_spent': 'Time Spent',
      'minutes': 'min',
      'seconds': 'sec',
      'attachments': 'Attachments',
      'add_photo': 'Add Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'attach_file': 'Attach File',
      'no_homework': 'No homework assigned',

      // Notes
      'lesson_notes': 'Lesson Notes',
      'add_note': 'Add Note',
      'edit_note': 'Edit Note',
      'note_text': 'Note content',
      'search_notes': 'Search notes...',
      'no_notes': 'No notes for this lesson',

      // Subjects & Bells
      'subjects': 'Subjects',
      'add_subject': 'Add Subject',
      'subject_name': 'Subject Name',
      'short_name': 'Short Name',
      'color': 'Color',
      'default_cabinet': 'Default Cabinet',
      'bells': 'Bell Schedule',
      'add_bell': 'Add Bell',
      'start_time': 'Start Time',
      'end_time': 'End Time',

      // Stats
      'statistics': 'Statistics',
      'weekly_overview': 'Weekly Overview',
      'study_time': 'Study Time',
      'homework_rate': 'HW Completion',
      'total_lessons': 'Total Lessons',
      'hours_short': 'h',
      'minutes_short': 'm',
      'busiest_subject': 'Busiest Subject',
      'total_hours': 'Total Study Time',
      'stats_subjects_count': 'Total Subjects',
      'stats_lessons_count': 'Lessons Scheduled',
      'stats_per_day': 'per day',
      'stats_homework_rate': 'Homework Rate',
      'stats_completed': 'completed',
      'stats_failed': 'failed',
      'stats_pending': 'pending',
      'stats_homework_time': 'Homework Time',
      'stats_avg_homework_time': 'avg. time per assignment',
      'stats_failed_title': 'Failed Homework in Class',
      'stats_failed_desc': 'Assignments marked as not completed on time',
      'stats_breaks_duration': 'Breaks Duration',
      'stats_cancelled_lessons': 'Cancelled Lessons',
      'stats_cancellation_reasons': 'Cancellation Reasons',
      'stats_reason_not_specified': 'Reason not specified',
      'stats_events_summary': 'Academic Events',
      'stats_mode_actual': 'Actual',
      'stats_mode_numerator': 'Numerator',
      'stats_mode_denominator': 'Denominator',
      'stats_metric_time': 'Time',
      'stats_metric_lessons': 'Lessons',
      'by_subjects': 'By Subjects',
      'by_days': 'By Days',
      'daily_breakdown': 'Daily Breakdown',
      'day_lessons': 'lessons',
      'day_no_lessons': 'No lessons scheduled',
      'no_data_week': 'No data for this week',
      'event_control_work': 'Control Work',
      'event_test': 'Test',
      'event_essay': 'Essay',
      'event_project': 'Project',
      'breaks_and_cancellations': 'Breaks & Schedule Interruptions',
      'duration': 'Duration',
      'hw_failed_badge': 'Failed',

      // Server & Sync
      'server_connection': 'Server Connection',
      'server_url': 'Server Address (Docker)',
      'server_url_hint': 'e.g. http://192.168.1.100:8080',
      'test_connection': 'Test Connection',
      'connection_ok': 'Connected successfully! Server is healthy.',
      'connection_failed': 'Could not connect to server.',
      'server_unreachable_title': 'Server Unreachable',
      'server_unreachable_desc': 'Could not reach server. Check local network IP or configure in Settings.',
      'configure_server_btn': 'Configure Address',
      'retry': 'Retry',
      'sync_status': 'Sync Status',
      'sync_now': 'Sync Now',
      'synced': 'Synced',
      'syncing': 'Syncing...',
      'auto_sync': 'Auto-Sync',
      'auto_sync_desc': 'Automatically refresh schedule and sync changes',
      'sync_interval': 'Auto-Sync Interval',
      'sync_interval_15s': '15s',
      'sync_interval_30s': '30s',
      'sync_interval_1m': '1m',
      'sync_interval_5m': '5m',
      'last_sync_time': 'Last synced',
      'just_now': 'just now',
      'seconds_ago': 's ago',
      'minutes_ago': 'm ago',
      'never_synced': 'never',
      'sync_success': 'Sync completed successfully',
      'sync_failed': 'Sync failed',
      'offline_mode': 'Offline Mode (Local Cache)',
      'pending_sync': 'Pending Sync Queue',
      'save_and_continue': 'Save & Continue',

      // Air Raid Alerts
      'air_raid_alert': 'Air Raid Alert',
      'alert_active': 'Warning! Air raid alert in your region!',
      'alert_calm': 'No active air raid alert',
      'select_region': 'Region for Alert Monitoring',

      // Common actions
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'language': 'Language',
      'theme': 'Theme',
      'theme_dark': 'Dark',
      'theme_light': 'Light',
      'theme_system': 'System',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['uk', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
